---
- name: Copy artifact to EC2
  become : True
  copy:
    src: "artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Start server
  become: True
  shell: |
    cd /home/ubuntu/
    tar -xvf artifact.tar.gz
    npm install
    pm2 stop default
    sudo pm2 start npm -- start
